In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('laptopprice.csv')

In [4]:
data.head()

brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
0    ASUS           Intel        Core i3            10th   4 GB     DDR4   
1  Lenovo           Intel        Core i3            10th   4 GB     DDR4   
2  Lenovo           Intel        Core i3            10th   4 GB     DDR4   
3    ASUS           Intel        Core i5            10th   8 GB     DDR4   
4    ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4   

      ssd      hdd       os  os_bit graphic_card_gb  weight     warranty  \
0    0 GB  1024 GB  Windows  64-bit            0 GB  Casual  No warranty   
1    0 GB  1024 GB  Windows  64-bit            0 GB  Casual  No warranty   
2    0 GB  1024 GB  Windows  64-bit            0 GB  Casual  No warranty   
3  512 GB     0 GB  Windows  32-bit            2 GB  Casual  No warranty   
4    0 GB   512 GB  Windows  64-bit            0 GB  Casual  No warranty   

  Touchscreen msoffice  Price   rating  Number of Ratings  Number of Reviews  
0          No       No  34649  2 stars                  3                  0  
1          No       No  38999  3 stars                 65                  5  
2          No       No  39999  3 stars                  8                  1  
3          No       No  69990  3 stars                  0                  0  
4          No       No  26990  3 stars                  0                  0

In [5]:
data.drop(columns = ["Number of Ratings"] , inplace = True)

In [6]:
data.drop(columns = ["Number of Reviews"] , inplace = True)

In [7]:
data.shape

(823, 17)

In [8]:
data.brand.unique()
data.rating.unique()
data.ram_type.unique()


array(['DDR4', 'LPDDR4', 'LPDDR4X', 'DDR5', 'DDR3', 'LPDDR3'],
      dtype=object)

In [9]:
data.dropna(inplace=True)

In [10]:
data.drop_duplicates(inplace=True)


In [11]:
data.shape

(792, 17)

In [12]:
data.drop(columns = ["msoffice"] , inplace = True)

In [13]:
data.drop(columns = ["weight"] , inplace = True)

In [14]:
data.drop(columns = ["Touchscreen"] , inplace = True)

In [15]:
data.drop(columns = ["ram_type"] , inplace = True)

In [16]:
data.drop(columns = ["warranty"] , inplace = True)

In [17]:
data.brand.unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [18]:
data.drop(columns = ["processor_brand"] , inplace = True)

In [19]:
data.drop(columns = ["processor_name"] , inplace = True)

In [20]:
data.drop(columns = ["brand"] , inplace = True)

In [21]:
data.drop(columns = ["rating"] , inplace = True)

In [22]:
data.head(1)

processor_gnrtn ram_gb   ssd      hdd       os  os_bit graphic_card_gb  \
0            10th   4 GB  0 GB  1024 GB  Windows  64-bit            0 GB   

   Price  
0  34649

In [23]:
data.ram_gb.unique()

array(['4 GB', '8 GB', '16 GB', '32 GB'], dtype=object)

In [24]:
data['ram_gb'] = data['ram_gb'].replace(['4 GB', '8 GB', '16 GB', '32 GB'],[4,8,16,32])

In [25]:
data.processor_gnrtn.unique()

array(['10th', 'Not Available', '11th', '7th', '8th', '9th', '4th',
       '12th'], dtype=object)

In [26]:
data = data[data['processor_gnrtn'] != 'Not Available']

In [27]:
data.processor_gnrtn.unique()

array(['10th', '11th', '7th', '8th', '9th', '4th', '12th'], dtype=object)

In [28]:
data['processor_gnrtn'] = data['processor_gnrtn'].replace(['10th', '11th', '7th', '8th', '9th', '4th', '12th'],[10,11,7,8,9,4,12])

In [29]:
data.ssd.unique()

array(['0 GB', '512 GB', '256 GB', '128 GB', '1024 GB', '2048 GB',
       '3072 GB'], dtype=object)

In [30]:
data['ssd'] = data['ssd'].replace(['0 GB', '512 GB', '256 GB', '128 GB', '1024 GB', '2048 GB',
       '3072 GB'],[0,512,256,128,1024,2048,3072])

In [31]:
data.hdd.unique()

array(['1024 GB', '0 GB', '512 GB', '2048 GB'], dtype=object)

In [32]:
data['hdd'] = data['hdd'].replace(['1024 GB', '0 GB', '512 GB', '2048 GB'],[1024,0,512,2048])

In [33]:
data.os.unique()

array(['Windows', 'DOS', 'Mac'], dtype=object)

In [34]:
data['os'] = data['os'].replace(['Windows', 'DOS', 'Mac'],[0,1,2])

In [35]:
data.os.unique()

array([0, 1, 2], dtype=int64)

In [36]:
data['os'] = data['os'].replace([64, 32,  2],[0,1,2])

In [37]:
data.os.unique()

array([0, 1, 2], dtype=int64)

In [38]:
data.os_bit.unique()

array(['64-bit', '32-bit'], dtype=object)

In [39]:
data['os_bit'] = data['os_bit'].replace(['64-bit', '32-bit'],[64,32])

In [40]:
data.os_bit.unique()

array([64, 32], dtype=int64)

In [41]:
data.graphic_card_gb.unique()

array(['0 GB', '2 GB', '4 GB', '6 GB', '8 GB'], dtype=object)

In [42]:
data['graphic_card_gb'] = data['graphic_card_gb'].replace(['0 GB', '2 GB', '4 GB', '6 GB', '8 GB'],[0,2,4,6,8])

In [43]:
data.graphic_card_gb.unique()

array([0, 2, 4, 6, 8], dtype=int64)

In [44]:
data.head(1)

processor_gnrtn  ram_gb  ssd   hdd  os  os_bit  graphic_card_gb  Price
0               10       4    0  1024   0      64                0  34649

In [45]:
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

import numpy as np

In [46]:
input = data.drop(columns=["Price"])
output = data['Price']

In [47]:
x_train,x_test,y_train,y_test = train_test_split(input,output,test_size=0.2)

In [48]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [49]:
model.score(x_test,y_test)

0.6625718421758211

In [50]:
data.head(9)

processor_gnrtn  ram_gb  ssd   hdd  os  os_bit  graphic_card_gb  Price
0                10       4    0  1024   0      64                0  34649
1                10       4    0  1024   0      64                0  38999
2                10       4    0  1024   0      64                0  39999
3                10       8  512     0   0      32                2  69990
7                10       8    0  1024   0      32                2  58799
8                10       4    0  1024   0      32                0  49999
9                10       4    0   512   0      32                4  59990
10               10       4    0   512   0      32                6  93700
11               10       4    0   512   0      32                4  72990

In [51]:
i = np.array([[10,4,1024,512,0,64,8]])
a = model.predict(i)

c:\Users\Sivaa\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [52]:
int(a[0])

138391

In [62]:
data.ssd.unique()

array([   0,  512,  256,  128, 1024, 2048, 3072], dtype=int64)

In [53]:
import pickle as pk
pk.dump(model,open("laptopprediction.pkl","wb"))